### ISSUE TITLE
[FEAT]: how can i change the color of the icons?

### ISSUE THREAD

**Issue by carlos-dubon** [shinokada/svelte-ionicons#2]
### Description

Is there a way to change the color of an icon? Through css or a prop?

**Comment by PrasoonPratham** [comment]
+1

**Comment by shinokada** [comment]
Unfortunately you can't change colors with svelte-ionicons.
But you can find more icons from https://svelte-svg-icons.vercel.app/.
Can you find one that suits your need?

**Comment by FlippingBinary** [comment]
If the icons have `fill` and `stroke` set to `currentColor` instead of `#000`, they will be the `color` set in CSS.

For example, this line: 
https://github.com/shinokada/svelte-ionicons/blob/70c6bb7d85e4e2ea9a396db346c874c5809f36a3/src/lib/Checkmark.svelte#L16

Could be changed to:
```css
		style="fill:none;stroke:currentColor;stroke-linecap:round;stroke-linejoin:round;stroke-width:32px"
```

Then someone can use `<Checkmark class="font-red-700" />` and it will be red (assuming that class is defined, of course). 

That's probably the easiest option to make these icons compatible with custom colors. I could do a pull request for it if you're receptive to it, @shinokada.

**Comment by shinokada** [comment]
I tried it as other icon sets. But it just doesn't look good so I decided not to add colors.
You can try and see how it looks.
And let me know.

**Comment by shinokada** [comment]
I added colors to icons.
